repos:
  - repo: local
    hooks:
      - id: black
        name: Black
        stages: [commit]
        language: system
        entry: black
        types: [python]

      - id: pylint
        name: PyLint
        stages: [commit]
        language: system
        entry: pylint --rcfile=.pylintrc
        files: \.py$
