# unique project identifier (required)
sonar.projectKey=outilscommuns:correlateurchaine3D:mc_cnn

# project metadata
sonar.projectName=MC_CNN
sonar.projectVersion=1.4.1

# path to source directories (required)
sonar.sources=src/mc_cnn

# path to test source directories (optional)
sonar.tests=tests

# path to pylint analysis report (optional)
#sonar.python.pylint.reportPath=pylint-report.txt

# set python version
sonar.python.version=3.10

# path to coverage report (optional)
sonar.python.coverage.reportPaths=reports/py-coverage.cobertura.xml
